### PR TITLE
Terraform scripts initial addition

### LINKED ISSUE #12: Develop IaC for Deployment
## 💡 Description

Develop the necessary documentation, terraform scripts and/or other definitions/scripts needed to deploy the app on a user system and deploying to the cloud.

### PR DESCRIPTION
**Pull request by collinss-jpl**
## 🗒️ Summary
This branch adds Terraform scripts to automate deployment of all AWS components of the Data Upload Manager

## ⚙️ Test Data and/or Report
One of the following should be included here:
* No changes to existing unit tests, but deployment has been tested in NGAP

## ♻️ Related Issues

Resolves #12

### CODE REVIEW

**Comment by collinss-jpl** [comment]
@nutjob4life The CI/CD is [failing when trying to execute a build_sphinx target](https://github.com/NASA-PDS/data-upload-manager/actions/runs/6115100189/job/16598019619#step:5:488). 

Any idea what might be causing this? I don't actually have any sphinx documentation to generate other than what comes with the template repo, so I don't really need a build_sphinx step to run anyhow...

**Comment by nutjob4life** [comment]
@collinss-jpl there was a bug in the Python template repository that left many packages unpinned.

If you update your `setup.cfg` with these lines it should work:

https://github.com/NASA-PDS/template-repo-python/blob/4bf2ae207e15e535cf2da3a3f6217af4e1003f21/setup.cfg#L60C1-L78

**Comment by collinss-jpl** [comment]
@nutjob4life That did the trick, thanks for your help as always!

**Comment by nutjob4life** [comment]
@collinss-jpl woot woot! 🎉

**Review by sjoshi-jpl — APPROVED** [review]
looks good to me!

**Pull request merged**
